// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"net/http"
	"week13/internal/biz"
	"week13/internal/data"
	"week13/internal/server"
	"week13/internal/service"
)

// Injectors from wire.go:

func InitializeHttpServer() *http.Server {
	db := data.NewMySqlDb()
	employeeRepo := data.NewEmployeeRepo(db)
	employee := biz.NewEmployee(employeeRepo)
	employeeServer := service.NewEmpService(employeeRepo, employee)
	httpServer := server.NewHttpServer(employeeServer)
	return httpServer
}
